import InnerTubeKit
import SwiftUI
import UIKit

/// The captions toggle (spec §10 Captions paragraph; plan §6.5) -- FitrahTube's own SwiftUI control,
/// same reasoning as `PlayerScreen.qualityMenu`/`AudioLanguageMenu`. Lists `tracks` (InnerTubeKit's
/// `captionTracks`, auto-generated ones only -- manual tracks ride AVKit's stock subtitle menu on
/// their own) plus an Off option; hidden entirely when `tracks` is empty. Auto-enables the first
/// track once, on this control's first appearance, when VoiceOver's closed-captioning setting is
/// already on (`captionsAutoEnableApplied` guards it from re-firing after a manual "Off" pick on a
/// later re-render/re-resolve within the same session).
///
/// B4 Task 3: extracted verbatim from `PlayerScreen.captionsMenu` so `ShortsScreen`'s rail and the
/// main player share ONE copy. Identifiers stay `player.*` -- B1's tests assert on them.
struct CaptionsMenu: View {
    let model: PlayerViewModel
    let tracks: [CaptionTrack]

    var body: some View {
        if !tracks.isEmpty {
            Menu {
                Section(String(localized: "player_captions_dialog_title")) {
                    Button {
                        model.selectedCaptionTrack = nil
                    } label: {
                        if model.selectedCaptionTrack == nil {
                            Label(String(localized: "player_captions_off"), systemImage: "checkmark")
                        } else {
                            Text(String(localized: "player_captions_off"))
                        }
                    }
                    .accessibilityIdentifier("player.captionsOption.off")

                    ForEach(tracks, id: \.languageCode) { track in
                        Button {
                            model.selectedCaptionTrack = track
                        } label: {
                            if model.selectedCaptionTrack == track {
                                Label(Self.captionLabel(track), systemImage: "checkmark")
                            } else {
                                Text(Self.captionLabel(track))
                            }
                        }
                        .accessibilityIdentifier("player.captionsOption.\(track.languageCode)")
                    }
                }
            } label: {
                Image(systemName: "captions.bubble").shortsGlyph()
            }
            .accessibilityIdentifier("player.captionsMenu.button")
            .accessibilityLabel(String(localized: "player_action_captions"))
            // Task 10: "Captions, Off" (spec §6.11 example, verbatim) when no track is selected,
            // else the selected track's own label.
            .accessibilityValue(model.selectedCaptionTrack.map(Self.captionLabel) ?? String(localized: "player_captions_off"))
            .task(id: tracks.map(\.languageCode)) {
                guard !model.captionsAutoEnableApplied else { return }
                model.captionsAutoEnableApplied = true
                if UIAccessibility.isClosedCaptioningEnabled, let first = tracks.first {
                    model.selectedCaptionTrack = first
                }
            }
        }
    }

    /// `"%1$@ (Auto-generated)"` for `kind=asr` tracks, else the bare language name.
    static func captionLabel(_ track: CaptionTrack) -> String {
        track.isAutoGenerated
            ? String(format: String(localized: "player_captions_auto_generated"), track.languageName)
            : track.languageName
    }
}
