package com.albunyaan.tube.data.extractor

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Parsing regression tests for the ANDROID_VR caption extraction added to
 * [AndroidVrStreamResolver]. The Oculus innertube response carries the same
 * `captions.playerCaptionsTracklistRenderer.captionTracks[]` block as the WEB
 * client; the resolver must surface it as [SubtitleTrack]s so the (already
 * built) CC button + side-loading light up on both players.
 *
 * Robolectric is required because real `org.json` parsing is only available
 * under it — the JVM stub returns default values (project convention; matches
 * sibling parser tests pinned to SDK 31).
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [31])
class AndroidVrSubtitleParsingTest {

    private fun playerJson(captionTracks: String): JSONObject = JSONObject(
        """{"captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[$captionTracks]}}}"""
    )

    @Test
    fun `parses caption tracks with language code, name and vtt format`() {
        val json = playerJson(
            """
            {"baseUrl":"https://www.youtube.com/api/timedtext?v=abc&fmt=srv3&lang=en","languageCode":"en","name":{"simpleText":"English"}},
            {"baseUrl":"https://www.youtube.com/api/timedtext?v=abc&fmt=srv3&lang=ar","languageCode":"ar","name":{"simpleText":"Arabic"}}
            """.trimIndent()
        )

        val tracks = AndroidVrStreamResolver.parseSubtitleTracks(json)

        assertEquals(2, tracks.size)
        assertEquals("en", tracks[0].languageCode)
        assertEquals("English", tracks[0].languageName)
        assertEquals("vtt", tracks[0].format)
        assertTrue("url must request WebVTT", tracks[0].url.contains("fmt=vtt"))
        assertFalse("srv3 must be replaced, not appended", tracks[0].url.contains("fmt=srv3"))
        assertEquals("ar", tracks[1].languageCode)
        assertEquals("Arabic", tracks[1].languageName)
    }

    @Test
    fun `marks asr tracks as auto-generated and reads name from runs`() {
        val json = playerJson(
            """
            {"baseUrl":"https://x/api/timedtext?fmt=srv3&kind=asr","languageCode":"en","kind":"asr","name":{"runs":[{"text":"English (auto-generated)"}]}},
            {"baseUrl":"https://x/api/timedtext?fmt=srv3","languageCode":"en","name":{"simpleText":"English"}}
            """.trimIndent()
        )

        val tracks = AndroidVrStreamResolver.parseSubtitleTracks(json)

        assertEquals(2, tracks.size)
        assertTrue("asr track is auto-generated", tracks[0].isAutoGenerated)
        assertEquals("English (auto-generated)", tracks[0].languageName)
        assertFalse("manual track is not auto-generated", tracks[1].isAutoGenerated)
    }

    @Test
    fun `absent captions block yields empty list`() {
        assertEquals(
            emptyList<SubtitleTrack>(),
            AndroidVrStreamResolver.parseSubtitleTracks(JSONObject("""{"streamingData":{}}"""))
        )
    }

    @Test
    fun `caption tracks missing baseUrl or languageCode are skipped`() {
        val json = playerJson(
            """
            {"languageCode":"en","name":{"simpleText":"No URL"}},
            {"baseUrl":"https://x/api/timedtext?fmt=srv3","name":{"simpleText":"No lang"}},
            {"baseUrl":"https://x/api/timedtext?fmt=srv3&lang=fr","languageCode":"fr","name":{"simpleText":"French"}}
            """.trimIndent()
        )

        val tracks = AndroidVrStreamResolver.parseSubtitleTracks(json)

        assertEquals(1, tracks.size)
        assertEquals("fr", tracks[0].languageCode)
    }

    @Test
    fun `falls back to language code when name is absent`() {
        val json = playerJson(
            """{"baseUrl":"https://x/api/timedtext?fmt=srv3&lang=nl","languageCode":"nl"}"""
        )

        val tracks = AndroidVrStreamResolver.parseSubtitleTracks(json)

        assertEquals(1, tracks.size)
        assertEquals("nl", tracks[0].languageName)
    }

    // ---- withVttFormat (pure URL rewriting; the srv3→vtt gotcha) ----

    @Test
    fun `withVttFormat replaces an existing fmt param in place`() {
        assertEquals(
            "https://x/api/timedtext?v=a&fmt=vtt&tlang=ar",
            AndroidVrStreamResolver.withVttFormat("https://x/api/timedtext?v=a&fmt=srv3&tlang=ar")
        )
    }

    @Test
    fun `withVttFormat appends fmt when the url has a query but no fmt`() {
        assertEquals(
            "https://x/api/timedtext?v=a&fmt=vtt",
            AndroidVrStreamResolver.withVttFormat("https://x/api/timedtext?v=a")
        )
    }

    @Test
    fun `withVttFormat appends fmt with a question mark when there is no query`() {
        assertEquals(
            "https://x/api/timedtext?fmt=vtt",
            AndroidVrStreamResolver.withVttFormat("https://x/api/timedtext")
        )
    }

    @Test
    fun `withVttFormat does not match fmt inside another param name`() {
        // Guards the ([?&]) anchor: a param like xfmt= must NOT be rewritten;
        // the real fmt must be appended instead.
        val out = AndroidVrStreamResolver.withVttFormat("https://x/api/timedtext?v=a&xfmt=q")
        assertTrue("real fmt must be appended", out.endsWith("&fmt=vtt"))
        assertTrue("the xfmt param must be left intact", out.contains("xfmt=q"))
    }

    @Test
    fun `caps the number of parsed caption tracks at MAX_CAPTION_TRACKS`() {
        // A pathological/hostile captionTracks[] must not fan out unbounded into
        // SingleSampleMediaSources downstream. Real videos stay far below the cap;
        // the 100+ auto-translate languages live in a separate array we never read.
        val oneTrack =
            """{"baseUrl":"https://www.youtube.com/api/timedtext?v=a&fmt=srv3&lang=en","languageCode":"en","name":{"simpleText":"English"}}"""
        val json = playerJson(List(250) { oneTrack }.joinToString(","))

        val tracks = AndroidVrStreamResolver.parseSubtitleTracks(json)

        assertEquals("must cap at MAX_CAPTION_TRACKS (100)", 100, tracks.size)
    }

    @Test
    fun `keeps exactly MAX_CAPTION_TRACKS at the boundary, no off-by-one`() {
        val oneTrack =
            """{"baseUrl":"https://www.youtube.com/api/timedtext?v=a&fmt=srv3&lang=en","languageCode":"en","name":{"simpleText":"English"}}"""
        // Exactly 100 valid tracks must all survive; 101 must clamp to 100.
        assertEquals(
            "exactly 100 must survive at the boundary",
            100,
            AndroidVrStreamResolver.parseSubtitleTracks(playerJson(List(100) { oneTrack }.joinToString(","))).size
        )
        assertEquals(
            "101 must clamp to 100",
            100,
            AndroidVrStreamResolver.parseSubtitleTracks(playerJson(List(101) { oneTrack }.joinToString(","))).size
        )
    }
}
