version: '3.8'

services:
  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-albunyaan-tube}
      - FIREBASE_EMULATOR_HOST=firebase-emulator:9099
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8082
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_ALBUNYAAN=DEBUG
    depends_on:
      - firebase-emulator
    volumes:
      - ./backend/src:/app/src
      - backend-cache:/root/.gradle
    networks:
      - albunyaan-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Firebase Emulator Suite
  firebase-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine
    ports:
      - "4000:4000"   # Emulator UI
      - "9099:9099"   # Auth
      - "8082:8082"   # Firestore
      - "9199:9199"   # Storage
      - "5001:5001"   # Functions
    environment:
      - FIRESTORE_PROJECT_ID=${FIREBASE_PROJECT_ID:-albunyaan-tube}
    volumes:
      - ./firebase-data:/firebase-data
      - ./firebase.json:/firebase.json:ro
      - ./.firebaserc:/.firebaserc:ro
    command: >
      sh -c "
        firebase emulators:start
        --project=${FIREBASE_PROJECT_ID:-albunyaan-tube}
        --import=/firebase-data
        --export-on-exit=/firebase-data
      "
    networks:
      - albunyaan-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  albunyaan-network:
    driver: bridge

volumes:
  backend-cache:
    driver: local
