import Foundation

/// A caption/subtitle track discovered on a stream (`extraction.md` §4).
public struct CaptionTrack: Sendable, Equatable {
    public var url: URL
    public var languageCode: String
    public var languageName: String
    public var isAutoGenerated: Bool

    public init(url: URL, languageCode: String, languageName: String, isAutoGenerated: Bool) {
        self.url = url
        self.languageCode = languageCode
        self.languageName = languageName
        self.isAutoGenerated = isAutoGenerated
    }
}

/// The playable result of resolving a videoId (spec §9).
public enum ResolvedStream: Sendable {
    case hls(url: URL, isLive: Bool, audioOnlyURL: URL?, captionTracks: [CaptionTrack])
    case progressive(url: URL, label: String)
    case embed(videoId: String)
    case openInYouTube(url: URL)
}

/// The InnerTube client family a resolve was performed under. The `userAgent`
/// that minted a stream's URLs must be reused on segment fetches or googlevideo
/// 403s (`StreamModels.kt:110-119`) — load-bearing even though a Task-1 probe
/// found no immediate mismatch failure.
public enum ClientFamily: Sendable {
    case visionos
    case android
    case web

    public var userAgentIsRequired: Bool {
        switch self {
        case .visionos, .android: return true
        case .web: return false
        }
    }
}

/// A resolved stream plus the context needed to play/expire it.
public struct Resolved: Sendable {
    public var stream: ResolvedStream
    public var client: ClientFamily
    public var userAgent: String
    public var resolvedAt: Date
    public var expiresAt: Date?

    public init(stream: ResolvedStream, client: ClientFamily, userAgent: String, resolvedAt: Date, expiresAt: Date?) {
        self.stream = stream
        self.client = client
        self.userAgent = userAgent
        self.resolvedAt = resolvedAt
        self.expiresAt = expiresAt
    }

    public func isExpired(now: Date) -> Bool {
        guard let expiresAt else { return false }
        return expiresAt <= now
    }
}

/// Errors surfaced by the resolve ladder. `transport` carries a `String`
/// (not the underlying `Error`) so the whole enum stays `Equatable`.
public enum ExtractionError: Error, Sendable, Equatable {
    case invalidVideoId
    case unavailable(videoId: String)
    case ageRestricted
    case geoBlocked
    case `private`
    case removed
    case liveOffline(startsAt: Date?)
    case botCheck
    case allRungsFailed
    case cancelled
    case transport(String)

    /// True for errors that will never succeed on retry (ruling 14).
    public var terminal: Bool {
        switch self {
        case .ageRestricted, .geoBlocked, .private, .removed, .unavailable, .liveOffline:
            return true
        case .invalidVideoId, .botCheck, .allRungsFailed, .cancelled, .transport:
            return false
        }
    }
}

/// The two resolve lanes (ruling 16).
public enum Purpose: Sendable {
    case player
    case prefetch
}
