import Foundation

/// The outcome of parsing a `player` InnerTube response body
/// (`extraction.md` §4, `ios-app-plan.md` §6.2 step 4).
public enum Playability: Sendable, Equatable {
    case ok(StreamingData)
    case unplayableKids
    case ageGate
    case botCheck
    case liveOffline(startsAt: Date?)
    case unavailable(reason: String)
}

/// Streaming data extracted from an `OK` player response.
public struct StreamingData: Sendable, Equatable {
    public var hlsManifestURL: URL?
    public var itag18URL: URL?
    public var itag140URL: URL?
    public var expiresInSeconds: Int?
    public var isLive: Bool
    public var captionTracks: [CaptionTrack]

    public init(
        hlsManifestURL: URL? = nil,
        itag18URL: URL? = nil,
        itag140URL: URL? = nil,
        expiresInSeconds: Int? = nil,
        isLive: Bool = false,
        captionTracks: [CaptionTrack] = []
    ) {
        self.hlsManifestURL = hlsManifestURL
        self.itag18URL = itag18URL
        self.itag140URL = itag140URL
        self.expiresInSeconds = expiresInSeconds
        self.isLive = isLive
        self.captionTracks = captionTracks
    }
}

/// Parses a raw `player` InnerTube response body into a `Playability`
/// (`ios-app-plan.md` §6.2 step 4 branching).
public struct PlayerResponseParser: Sendable {
    public init() {}

    public func parse(_ body: Data) throws -> Playability {
        let wire = try JSONDecoder().decode(Wire.self, from: body)
        let status = wire.playabilityStatus.status
        let reason = wire.playabilityStatus.reason ?? status

        switch status {
        case "OK":
            return .ok(streamingData(from: wire))
        case "LOGIN_REQUIRED", "AGE_CHECK_REQUIRED":
            let lowered = reason.lowercased()
            if lowered.contains("age") {
                return .ageGate
            }
            if lowered.contains("bot") {
                return .botCheck
            }
            return .unavailable(reason: reason)
        case "UNPLAYABLE":
            return .unplayableKids
        case "LIVE_STREAM_OFFLINE":
            // ponytail: no LIVE_STREAM_OFFLINE probe capture exists to confirm the scheduled-start
            // JSON path, so `startsAt` is always nil for now. Upgrade once a probe fixture exists.
            return .liveOffline(startsAt: nil)
        default:
            return .unavailable(reason: reason)
        }
    }

    private func streamingData(from wire: Wire) -> StreamingData {
        let formats = wire.streamingData?.formats ?? []
        return StreamingData(
            hlsManifestURL: wire.streamingData?.hlsManifestUrl.flatMap(URL.init(string:)),
            itag18URL: url(forItag: 18, in: formats),
            itag140URL: url(forItag: 140, in: formats),
            expiresInSeconds: wire.streamingData?.expiresInSeconds.flatMap(Int.init),
            isLive: wire.videoDetails?.isLive ?? wire.videoDetails?.isLiveContent ?? false,
            captionTracks: captionTracks(from: wire.captions)
        )
    }

    private func url(forItag itag: Int, in formats: [Wire.Format]) -> URL? {
        formats.first(where: { $0.itag == itag })?.url.flatMap(URL.init(string:))
    }

    private func captionTracks(from captions: Wire.Captions?) -> [CaptionTrack] {
        let tracks = captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
        return tracks.compactMap { track in
            guard let baseUrl = track.baseUrl, let url = URL(string: baseUrl + "&fmt=vtt") else { return nil }
            let languageCode = track.languageCode ?? ""
            let languageName = track.name?.runs?.first?.text ?? languageCode
            return CaptionTrack(url: url, languageCode: languageCode, languageName: languageName, isAutoGenerated: track.kind == "asr")
        }
    }

    /// Only the fields this parser reads, tolerant of missing keys (Codable's default
    /// behaviour for `Optional` properties).
    private struct Wire: Decodable {
        struct PlayabilityStatus: Decodable {
            var status: String
            var reason: String?
        }
        struct Format: Decodable {
            var itag: Int?
            var url: String?
        }
        struct StreamingData: Decodable {
            var expiresInSeconds: String?
            var hlsManifestUrl: String?
            var formats: [Format]?
        }
        struct CaptionTrackWire: Decodable {
            var baseUrl: String?
            var languageCode: String?
            var name: Name?
            var kind: String?

            struct Name: Decodable {
                var runs: [Run]?
            }
            struct Run: Decodable {
                var text: String?
            }
        }
        struct CaptionsTracklistRenderer: Decodable {
            var captionTracks: [CaptionTrackWire]?
        }
        struct Captions: Decodable {
            var playerCaptionsTracklistRenderer: CaptionsTracklistRenderer?
        }
        struct VideoDetails: Decodable {
            var isLive: Bool?
            var isLiveContent: Bool?
        }

        var playabilityStatus: PlayabilityStatus
        var streamingData: StreamingData?
        var captions: Captions?
        var videoDetails: VideoDetails?
    }
}
