package com.albunyaan.tube.service;

import org.junit.jupiter.api.Test;
import org.schabi.newpipe.extractor.services.youtube.protos.playlist.PlaylistProtobufContinuation;

import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * NewPipeExtractor ships classes generated by its own protobuf version, but this
 * project excludes its protobuf-javalite (see build.gradle.kts) and runs them on
 * the protobuf-java runtime resolved from the Firebase/Firestore stack — an
 * officially unsupported direction whenever the generated code is newer than the
 * runtime (https://protobuf.dev/support/cross-version-runtime-guarantee/), which
 * is why build.gradle.kts constrains protobuf-java to NewPipe's generator version.
 *
 * Scope honesty: lite-generated code does not run the gencode-version check, so
 * this test does NOT detect soft version drift (verified: it passes even on a
 * protobuf-java 3.25.5 runtime). What it does catch is linkage-level breakage —
 * ClassNotFound/NoSuchMethodError when a runtime bump drops or reshapes the lite
 * support APIs — on the playlist-continuation classes, a production path
 * (YouTubeGateway playlist pagination) the rest of the suite never loads.
 */
class NewPipeProtobufRuntimeCompatTest {

    @Test
    void newPipeGeneratedMessageWorksOnResolvedProtobufRuntime() throws Exception {
        var message = PlaylistProtobufContinuation.PlaylistContinuation.getDefaultInstance();
        byte[] bytes = message.toByteArray();
        assertNotNull(PlaylistProtobufContinuation.PlaylistContinuation.parseFrom(bytes));
    }
}
