package com.albunyaan.tube.ui.shared

import android.app.Dialog
import android.os.Bundle
import androidx.core.os.bundleOf
import androidx.fragment.app.DialogFragment
import androidx.fragment.app.setFragmentResult
import com.albunyaan.tube.R
import com.google.android.material.dialog.MaterialAlertDialogBuilder

/**
 * Single-choice dialog listing the subtitle/caption tracks NewPipe surfaced for
 * the currently-bound video. The first item is always "Off" (disables subtitles,
 * result = null). Selection is posted back via Fragment Result API — the hosting
 * fragment listens on [REQUEST_KEY] and reads [RESULT_SELECTED_CODE] (null means
 * subtitles off).
 *
 * The dialog itself is stateless; all labels and the currently-selected language
 * code are passed via arguments so the dialog survives process death (Bundle-safe).
 */
class SubtitlePickerDialog : DialogFragment() {

    override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        val codes = arguments?.getStringArray(ARG_CODES).orEmpty()
        val names = arguments?.getStringArray(ARG_NAMES).orEmpty()
        val autoGenerated = arguments?.getBooleanArray(ARG_AUTO_GENERATED)
            ?: BooleanArray(codes.size)
        val currentCode = arguments?.getString(ARG_CURRENT_CODE)

        // Build display labels: "Off" first, then track names with optional "(auto)" suffix
        val offLabel = getString(R.string.player_captions_off)
        val trackLabels = Array(codes.size) { i ->
            val base = names.getOrNull(i).orEmpty()
            if (autoGenerated.getOrNull(i) == true) {
                getString(R.string.player_captions_auto_generated, base)
            } else {
                base
            }
        }
        val allLabels = arrayOf(offLabel, *trackLabels)

        // "Off" is index 0; actual tracks start at index 1
        val checkedIndex = if (currentCode == null) {
            0
        } else {
            val trackIndex = codes.indexOfFirst { it == currentCode }
            if (trackIndex >= 0) trackIndex + 1 else 0
        }

        return MaterialAlertDialogBuilder(requireContext())
            .setTitle(R.string.player_captions_dialog_title)
            .setSingleChoiceItems(allLabels, checkedIndex) { dialog, which ->
                val selectedCode: String? = if (which == 0) null else codes.getOrNull(which - 1)
                setFragmentResult(
                    REQUEST_KEY,
                    bundleOf(RESULT_SELECTED_CODE to selectedCode)
                )
                dialog.dismiss()
            }
            .setNegativeButton(android.R.string.cancel, null)
            .create()
    }

    companion object {
        const val TAG = "SubtitlePickerDialog"
        const val REQUEST_KEY = "subtitle_picker_request"
        const val RESULT_SELECTED_CODE = "selected_language_code"

        private const val ARG_CODES = "codes"
        private const val ARG_NAMES = "names"
        private const val ARG_AUTO_GENERATED = "auto_generated"
        private const val ARG_CURRENT_CODE = "current_code"

        /**
         * @param tracks ordered list of `(languageCode, languageName, isAutoGenerated)`
         * @param currentCode language code currently active, or null if subtitles are off
         */
        fun newInstance(
            tracks: List<Triple<String, String, Boolean>>,
            currentCode: String?
        ): SubtitlePickerDialog {
            val codes = tracks.map { it.first }.toTypedArray()
            val names = tracks.map { it.second }.toTypedArray()
            val autoGenerated = BooleanArray(tracks.size) { tracks[it].third }
            return SubtitlePickerDialog().apply {
                arguments = bundleOf(
                    ARG_CODES to codes,
                    ARG_NAMES to names,
                    ARG_AUTO_GENERATED to autoGenerated,
                    ARG_CURRENT_CODE to currentCode
                )
            }
        }
    }
}
