import Foundation
import InnerTubeKit
import Testing
@testable import FitrahTube

/// Spec §10 Captions paragraph / plan §6.5: parser + active-cue selection for auto-generated
/// caption overlays. `Cue`/`parseVTT`/`activeCue` are pure, so they're driven directly with a
/// fixture string -- no simulator/AVFoundation dependency.
@Suite(.perTest)
struct CaptionsProviderTests {
    /// Header, a `NOTE` block (skipped), a cue with an inline `<c>` tag, a multi-line cue, and an
    /// hour-form (`hh:mm:ss.mmm`) timestamp with an inline `<v Speaker>` tag and trailing cue
    /// settings on its timing line.
    private static let fixture = """
    WEBVTT

    NOTE
    This is a note and must never become a cue.

    00:00:01.000 --> 00:00:04.000
    Hello <c>world</c>

    00:00:05.000 --> 00:00:07.500
    Line one
    Line two

    01:02:03.456 --> 01:02:06.000 align:start position:10%
    <v Speaker>Final cue text
    """

    private static func parsed() -> [CaptionsProvider.Cue] { CaptionsProvider.parseVTT(fixture) }

    // MARK: - Parser

    @Test func parsesEveryCueSkippingTheHeaderAndNoteBlock() {
        #expect(Self.parsed().count == 3)
    }

    @Test func stripsInlineTagsFromCueText() {
        #expect(Self.parsed()[0] == CaptionsProvider.Cue(start: 1, end: 4, text: "Hello world"))
    }

    @Test func joinsMultiLineCueTextWithNewlines() {
        #expect(Self.parsed()[1] == CaptionsProvider.Cue(start: 5, end: 7.5, text: "Line one\nLine two"))
    }

    @Test func parsesHourFormTimestampsAndStripsTrailingCueSettings() {
        #expect(Self.parsed()[2] == CaptionsProvider.Cue(start: 3723.456, end: 3726, text: "Final cue text"))
    }

    @Test func emptyInputParsesToNoCues() {
        #expect(CaptionsProvider.parseVTT("").isEmpty)
        #expect(CaptionsProvider.parseVTT("WEBVTT\n").isEmpty)
    }

    // MARK: - Active-cue selection

    @Test func timeInsideACueReturnsThatCue() {
        let cues = Self.parsed()
        #expect(CaptionsProvider.activeCue(cues, at: 6) == cues[1])
    }

    @Test func timeBetweenCuesReturnsNil() {
        #expect(CaptionsProvider.activeCue(Self.parsed(), at: 4.5) == nil)
    }

    @Test func timeBeforeTheFirstCueReturnsNil() {
        #expect(CaptionsProvider.activeCue(Self.parsed(), at: 0.5) == nil)
    }

    @Test func timeAfterTheLastCueReturnsNil() {
        #expect(CaptionsProvider.activeCue(Self.parsed(), at: 4000) == nil)
    }

    @Test func cueStartIsInclusiveAndEndIsExclusive() {
        let cues = Self.parsed()
        #expect(CaptionsProvider.activeCue(cues, at: cues[0].start) == cues[0])
        #expect(CaptionsProvider.activeCue(cues, at: cues[0].end) == nil)
    }

    // MARK: - Fetch (injected transport seam, no network)

    private struct StubTransport: HTTPTransport {
        var status: Int = 200
        var body: String

        func send(_ request: HTTPRequest) async throws -> HTTPResponse {
            HTTPResponse(status: status, headers: [:], body: Data(body.utf8))
        }
    }

    private static let track = CaptionTrack(
        url: URL(string: "https://example.com/timedtext?fmt=vtt")!,
        languageCode: "ar", languageName: "Arabic", isAutoGenerated: true)

    @Test func fetchesAndParsesTheTrackURLThroughTheInjectedTransport() async throws {
        let provider = CaptionsProvider(transport: StubTransport(body: Self.fixture))
        let cues = try await provider.cues(for: Self.track)
        #expect(cues == Self.parsed())
    }

    @Test func nonOKStatusYieldsNoCues() async throws {
        let provider = CaptionsProvider(transport: StubTransport(status: 404, body: "Not Found"))
        let cues = try await provider.cues(for: Self.track)
        #expect(cues.isEmpty)
    }
}

/// Fix round 1 F1: `PlayerScreen.captionTracks(_:)` must filter `captionTracks` down to
/// auto-generated only -- manual tracks ride AVKit's stock subtitle menu, and this menu's
/// `tracks.first` auto-enable pick must never land on a manual track.
@Suite(.perTest)
struct PlayerScreenCaptionsTests {
    private static func track(_ code: String, auto: Bool) -> CaptionTrack {
        CaptionTrack(url: URL(string: "https://example.com/\(code).vtt")!, languageCode: code,
                     languageName: code, isAutoGenerated: auto)
    }

    private static func resolved(_ tracks: [CaptionTrack]) -> Resolved {
        Resolved(stream: .hls(url: URL(string: "https://example.com/master.m3u8")!, isLive: false,
                              audioOnlyURL: nil, captionTracks: tracks),
                 client: .visionos, userAgent: "UA", resolvedAt: Date(), expiresAt: nil)
    }

    @Test func filtersOutManualTracksKeepingOnlyAutoGenerated() {
        let manual = Self.track("en", auto: false)
        let asr1 = Self.track("ar", auto: true)
        let asr2 = Self.track("fr", auto: true)
        let result = PlayerScreen.captionTracks(.ready(Self.resolved([manual, asr1, asr2])))
        #expect(result == [asr1, asr2])
    }

    /// The menu/auto-enable's `tracks.first` must land on the first ASR track, not the manual one
    /// that leads the raw (unfiltered) list.
    @Test func autoEnablePickIsTheFirstAutoGeneratedTrackNotTheLeadingManualOne() {
        let manual = Self.track("en", auto: false)
        let asr = Self.track("ar", auto: true)
        let result = PlayerScreen.captionTracks(.ready(Self.resolved([manual, asr])))
        #expect(result.first == asr)
    }

    @Test func noAutoGeneratedTracksYieldsAnEmptyMenuList() {
        let manual = Self.track("en", auto: false)
        #expect(PlayerScreen.captionTracks(.ready(Self.resolved([manual]))).isEmpty)
    }

    @Test func rung2ProgressiveHasNoCaptionTracks() {
        let progressive = Resolved(stream: .progressive(url: URL(string: "https://example.com/a.mp4")!, label: "360p"),
                                   client: .visionos, userAgent: "UA", resolvedAt: Date(), expiresAt: nil)
        #expect(PlayerScreen.captionTracks(.rung2Progressive(progressive)).isEmpty)
    }
}
