import CoreGraphics
import Foundation
import InnerTubeKit
import Testing
@testable import FitrahTube

/// B4 Task 2: the Shorts surface reuses `PlayerViewModel` unchanged, so what this suite pins is the
/// one contract the screen adds on top -- a single short resolves exactly itself.
@Suite(.perTest)
struct ShortsScreenTests {
    private func makeSettings() -> UserDefaultsSettingsStore {
        UserDefaultsSettingsStore(defaults: UserDefaults(suiteName: "ShortsScreenTests.\(UUID().uuidString)")!)
    }

    @Test func shortsResolveTheCurrentItemAndNothingElse() async {
        // Plan 6.2 ("Shorts: resolve the current item only") + CF-B2-2 (.prefetch is B5's lane).
        // Opening the screen's view model must produce EXACTLY ONE resolve -- no neighbour, no
        // speculative warm-up -- on the interactive lane, uncached-forcing nothing.
        let resolver = RecordingResolver(.hls)
        let model = PlayerViewModel(resolver: resolver, settings: makeSettings(),
                                    args: PlayerArgs(videoId: "short1"))
        await model.open()
        #expect(resolver.calls.count == 1)
        #expect(resolver.calls[0].forceRefresh == false)
        #expect(resolver.calls[0].kind == .player)
        #expect(resolver.calls[0].purpose == .player)
        // Ceiling (M7, fix round 2): this drives `PlayerViewModel.open()` directly. A prefetch added
        // in `ShortsScreen.task` (outside the view model) would NOT be caught here.
    }

    /// C1 (fix round 2): `.embed` online must reach `EmbedRungView`, never `PlayerStateView` --
    /// `PlayerStateCopy.map` `preconditionFailure`s on an online `.embed`. Offline it is the
    /// offline card, the same rule `PlayerScreen` follows.
    @Test func embedRoutesToTheEmbedRungOnlineAndTheStatusCardOffline() {
        let resolved = Resolved(stream: .embed(videoId: "xc7keR2piUM"), client: .web, userAgent: "",
                                resolvedAt: Date(), expiresAt: nil)
        #expect(ShortsScreen.branch(for: .embed(resolved), isOnline: true) == .embed)
        #expect(ShortsScreen.branch(for: .embed(resolved), isOnline: false) == .status)
        #expect(ShortsScreen.branch(for: .ready(resolved), isOnline: true) == .player)
        #expect(ShortsScreen.branch(for: .loading, isOnline: true) == .status)
    }

    // MARK: - Task 3: chrome

    @Test func scrubMathsRoundTripsAndSurvivesADegenerateDuration() {
        #expect(ShortsScrub.progress(current: 15, duration: 60) == 0.25)
        #expect(ShortsScrub.time(progress: 0.25, duration: 60) == 15)
        // A live/unknown duration is 0 or NaN on a real AVPlayerItem; the bar must clamp, not divide.
        #expect(ShortsScrub.progress(current: 15, duration: 0) == 0)
        #expect(ShortsScrub.progress(current: 15, duration: .nan) == 0)
        #expect(ShortsScrub.time(progress: 2.0, duration: 60) == 60)   // clamped, never seeks past end
    }

    @Test func theScrubberClockNeverTrapsOnANonFiniteTime() {
        // I3 (Task 3 review): `Int64(time.seconds)` traps on NaN/inf, and a live AVPlayerItem hands
        // the periodic observer exactly that before its duration is known. `Format.duration` is the
        // one m:ss formatter (rung 2 of the ladder); the guard here is the only new logic.
        #expect(ShortsScrub.clock(.nan) == "0:00")
        #expect(ShortsScrub.clock(.infinity) == "0:00")
        #expect(ShortsScrub.clock(-.infinity) == "0:00")
        #expect(ShortsScrub.clock(90.9) == "1:30")
    }

    @Test func theChannelRowHidesItselfWhenTheShortCarriesNoChannel() {
        // ShortsPageViewHolder.kt:44-60 -- feed/deep-link mode "often lacks channelName", and an "@"
        // with nothing after it is worse than no row. Blank, not just nil: Android checks isBlank.
        #expect(ShortsOverlay.showsChannelRow(channelName: "Ustadh Example"))
        #expect(ShortsOverlay.showsChannelRow(channelName: nil) == false)
        #expect(ShortsOverlay.showsChannelRow(channelName: "   ") == false)
    }

    @Test func theEmbedRungIsTheOnlyThingThatChangesShapeForShorts() {
        // CF-B3-1: the aspect ratio is the ONE parameter. Its default keeps every B3 call site 16:9.
        #expect(EmbedRungView.defaultAspectRatio == 16.0 / 9.0)
        // The 200x200 pt floor at 9:16, on the narrowest portrait-locked geometry this app supports.
        #expect(EmbedRungView.fittedSize(container: CGSize(width: 320, height: 568),
                                         aspectRatio: 9.0 / 16.0).width >= 200)
    }

    @Test func captionsMenuIsTheOneCopyBothScreensUse() {
        // The extraction must not change what PlayerScreen renders: same label rule, same filter.
        let asr = CaptionTrack(url: URL(string: "https://x")!, languageCode: "en", languageName: "English", isAutoGenerated: true)
        #expect(CaptionsMenu.captionLabel(asr)
                == String(format: String(localized: "player_captions_auto_generated"), "English"))
    }
}
