package com.albunyaan.tube.audit;

public enum AuditAction {
    MODERATION_APPROVED,
    MODERATION_REJECTED,
    REGISTRY_CHANNEL_INCLUDED,
    REGISTRY_CHANNEL_EXCLUDED,
    REGISTRY_PLAYLIST_INCLUDED,
    REGISTRY_PLAYLIST_EXCLUDED,
    REGISTRY_VIDEO_INCLUDED,
    REGISTRY_VIDEO_EXCLUDED
}
