import Foundation
import Testing
@testable import InnerTubeKit

@Suite struct PlayerResponseParserTests {
    private let parser = PlayerResponseParser()

    @Test func okHlsFixtureYieldsPlayableStreamingData() throws {
        let result = try parser.parse(try loadFixture("player-ok-hls")).playability
        switch result {
        case .ok(let streaming):
            #expect(streaming.hlsManifestURL != nil)
            #expect(streaming.expiresInSeconds == 21540)
            // The real capture has NO `formats` key at all -- itag 140 (audio-only m4a) lives in
            // `adaptiveFormats`, which is why `audioOnlyURL` was permanently nil (CF-B2).
            let audioOnly = try #require(streaming.itag140URL)
            #expect(audioOnly.host()?.hasSuffix("googlevideo.com") == true)
            #expect(audioOnly.path == "/videoplayback")
            // Real Arabic ASR caption track; baseUrl already has a `?...` query string, so the
            // parser must append with `&`, not `?`.
            #expect(streaming.captionTracks.count == 1)
            let caption = try #require(streaming.captionTracks.first)
            #expect(caption.url.absoluteString.hasSuffix("&fmt=vtt"))
            #expect(caption.isAutoGenerated)
            #expect(caption.languageName == "Arabic (auto-generated)")
        default:
            Issue.record("expected .ok, got \(result)")
        }
    }

    // The real capture (Task 1 probe) is UNPLAYABLE with no streamingData at all — the
    // androidItag18 fallback comes from a *separate* ANDROID-client request per
    // ios-app-plan.md §6.2 step 4, out of scope for parsing one response body. `.unplayableKids`
    // also carries no associated payload, so there is no itag18 URL to assert here.
    @Test func unplayableKidsFixtureYieldsUnplayableKids() throws {
        let result = try parser.parse(try loadFixture("player-unplayable-kids")).playability
        #expect(result == .unplayableKids)
    }

    @Test func ageGatedFixtureYieldsAgeGate() throws {
        let result = try parser.parse(try loadFixture("player-age-gated")).playability
        #expect(result == .ageGate)
    }

    @Test func liveFixtureYieldsPlayableLiveStreamingData() throws {
        let result = try parser.parse(try loadFixture("player-live")).playability
        switch result {
        case .ok(let streaming):
            #expect(streaming.isLive)
            #expect(streaming.hlsManifestURL != nil)
        default:
            Issue.record("expected .ok, got \(result)")
        }
    }

    // Synthetic (inline, not a fixture): the archived-livestream case — YouTube sets
    // `videoDetails.isLiveContent = true` forever once a video has ever been live, but the
    // specific `isLive` flips to `false` once the broadcast ends. The parser must prefer `isLive`
    // over the sticky `isLiveContent`.
    // Deviation from the fix-round request: written with `isLive` explicitly `false`, not absent.
    // With the specified fallback (`isLive ?? isLiveContent ?? false`), an *absent* isLive key
    // falls through to `isLiveContent` and correctly yields `true` per that formula — only an
    // explicit `isLive: false` exercises the "no longer live" case this fix targets.
    @Test func archivedLivestreamPrefersIsLiveOverStickyIsLiveContent() throws {
        let body = Data(
            """
            {"playabilityStatus": {"status": "OK"}, "videoDetails": {"isLive": false, "isLiveContent": true}}
            """.utf8)
        let result = try parser.parse(body).playability
        switch result {
        case .ok(let streaming):
            #expect(!streaming.isLive)
        default:
            Issue.record("expected .ok, got \(result)")
        }
    }

    // §6.3's session token: present on every real capture, absent from a body without a
    // responseContext (the parser must not invent one).
    @Test func parseSurfacesResponseContextVisitorData() throws {
        let ok = try parser.parse(try loadFixture("player-ok-hls"))
        #expect(ok.visitorData?.hasPrefix("CgtIdEVOUkk0ZHIwVSi") == true)
        let synthetic = try parser.parse(Data(#"{"playabilityStatus": {"status": "OK"}}"#.utf8))
        #expect(synthetic.visitorData == nil)
    }

    // M2 defense-in-depth: a non-https manifest/format URL is dropped to nil so AVPlayer never
    // sees a plain-http or spoofable URL — the field reads as absent and the ladder advances.
    @Test func nonHttpsManifestAndFormatURLsAreTreatedAsAbsent() throws {
        let body = Data(
            """
            {"playabilityStatus": {"status": "OK"}, "streamingData": {"hlsManifestUrl": "http://insecure.example.com/m.m3u8", "formats": [{"itag": 18, "url": "http://insecure.example.com/v?itag=18"}]}, "videoDetails": {"isLive": false}}
            """.utf8)
        let result = try parser.parse(body).playability
        switch result {
        case .ok(let streaming):
            #expect(streaming.hlsManifestURL == nil)
            #expect(streaming.itag18URL == nil)
        default:
            Issue.record("expected .ok, got \(result)")
        }
    }

    @Test func botcheckFixtureYieldsBotCheck() throws {
        let result = try parser.parse(try loadFixture("player-botcheck")).playability
        #expect(result == .botCheck)
    }

    // Synthetic fixture (not probe-captured — the embed-only case wasn't reproducible live in
    // Task 1): a response missing `streamingData` entirely, with a non-branching status.
    @Test func embedOnlyFixtureMissingStreamingDataYieldsUnavailable() throws {
        let result = try parser.parse(try loadFixture("player-embed-only")).playability
        #expect(result == .unavailable(reason: "This video is unavailable"))
    }

    // CF-B2: itag 140 is an ADAPTIVE format. Synthetic bodies (shape derived from the real
    // `player-ok-hls` capture: `streamingData.adaptiveFormats[].{itag,url}`) so the lookup order
    // and the https guard can be asserted without a 74 KB fixture per case.
    @Test func parsesItag140FromAdaptiveFormats() throws {
        let body = Data(
            """
            {"playabilityStatus":{"status":"OK"},"streamingData":{"hlsManifestUrl":"https://manifest.googlevideo.com/x.m3u8","formats":[{"itag":18,"url":"https://r1.googlevideo.com/v18"}],"adaptiveFormats":[{"itag":140,"url":"https://r1.googlevideo.com/a140"},{"itag":137,"url":"https://r1.googlevideo.com/v137"}]}}
            """.utf8)
        let result = try parser.parse(body).playability
        switch result {
        case .ok(let streaming):
            #expect(streaming.itag140URL?.absoluteString == "https://r1.googlevideo.com/a140")
            #expect(streaming.itag18URL?.absoluteString == "https://r1.googlevideo.com/v18")
        default:
            Issue.record("expected .ok, got \(result)")
        }
    }

    @Test func itag140IsNilWhenNoAudioOnlyFormatExists() throws {
        let body = Data(
            """
            {"playabilityStatus":{"status":"OK"},"streamingData":{"hlsManifestUrl":"https://manifest.googlevideo.com/x.m3u8","adaptiveFormats":[{"itag":137,"url":"https://r1.googlevideo.com/v137"}]}}
            """.utf8)
        let result = try parser.parse(body).playability
        switch result {
        case .ok(let streaming):
            #expect(streaming.itag140URL == nil)
        default:
            Issue.record("expected .ok, got \(result)")
        }
    }

    @Test func itag140MustBeHTTPS() throws {
        let body = Data(
            """
            {"playabilityStatus":{"status":"OK"},"streamingData":{"hlsManifestUrl":"https://manifest.googlevideo.com/x.m3u8","adaptiveFormats":[{"itag":140,"url":"http://r1.googlevideo.com/a140"}]}}
            """.utf8)
        let result = try parser.parse(body).playability
        switch result {
        case .ok(let streaming):
            // httpsURL() drops non-https at the trust boundary (M2).
            #expect(streaming.itag140URL == nil)
        default:
            Issue.record("expected .ok, got \(result)")
        }
    }

    private func loadFixture(_ name: String) throws -> Data {
        let url = try #require(Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures"))
        return try Data(contentsOf: url)
    }
}
